// 1sem/trvp/lab1/vue/src/pages/Cart.vue
<script>
import { ref, onMounted } from "vue";
import Card from "../components/Card.vue";
import Form from "../components/Form.vue";
import { PRODUCTS_LIST } from "../data";

export default {
  name: "Cart",
  components: {
    Card,
    Form,
  },
  setup() {
    const cart = ref([]);
    const cartItems = ref([]);

    const loadCart = () => {
      cart.value = JSON.parse(localStorage.getItem("cart") || "[]");

      let allProducts = [];
      PRODUCTS_LIST.forEach(({ products }) => {
        allProducts.push(...products);
      });

      cartItems.value = allProducts.filter(({ id }) => cart.value.includes(id));
    };

    onMounted(() => {
      loadCart();
    });

    return {
      cartItems,
    };
  },
};
</script>

<template>
  <div class="cart">
    <div class="cart_products">
      <Card v-for="product in cartItems" :key="product.id" :product="product" />
    </div>
    <div class="cart_delivery">
      <Form />
    </div>
  </div>
</template>

// 1sem/trvp/lab1/react/src/pages/Cart.tsx
import { Card, Form } from "../components";
import { PRODUCTS_LIST } from "../data";
import { Product } from "../types";

export const Cart = () => {
  const cart: number[] = JSON.parse(localStorage.getItem("cart") as string);
  let cartItems: Product[] = [];
  PRODUCTS_LIST.forEach(({ products }) => cartItems.push(...products));

  cartItems = cartItems.filter(({ id }) => cart.includes(id));

  return (
    <div className="cart">
      <div className="cart_products">
        {cartItems.map((product) => (
          <Card product={product} key={product.id} />
        ))}
      </div>
      <div className="cart_delivery">
        <Form />
      </div>
    </div>
  );
};
