// 1sem/trvp/lab1/vue/src/ui/Button.vue
<script>
export default {
  name: "Button",
  props: {
    isOrange: {
      type: Boolean,
      default: false,
    },
    onClick: {
      type: Function,
      default: null,
    },
  },
  methods: {
    handleClick(event) {
      if (this.onClick) {
        this.onClick(event);
      }
    },
  },
};
</script>

<template>
  <button
    :class="['ui_Button', { 'ui_Button-orange': isOrange }]"
    @click="handleClick"
  >
    <slot></slot>
  </button>
</template>

// 1sem/trvp/lab1/react/src/ui/Button.tsx
import { FC, PropsWithChildren, SyntheticEvent } from "react";

type ButtonProps = {
  isOrange?: boolean;
  onClick?: (event: SyntheticEvent) => void;
};

export const Button: FC<PropsWithChildren<ButtonProps>> = ({
  children,
  isOrange,
  onClick,
}) => {
  return (
    <button
      className={`ui_Button ${isOrange && "ui_Button-orange"}`}
      onClick={onClick}
    >
      {children}
    </button>
  );
};
