// 1sem/trvp/lab1/vue/src/ui/Layout.vue
<script>
import { RouterLink, RouterView } from "vue-router";
import Button from "./Button.vue";

export default {
  name: "Layout",
  components: {
    RouterLink,
    RouterView,
    Button,
  },
};
</script>

<template>
  <div>
    <header>
      <RouterLink to="/">СЕВЕРЯНОЧКА</RouterLink>

      <RouterLink to="/cart">
        <Button isOrange>Корзина</Button>
      </RouterLink>
    </header>

    <main>
      <RouterView />
    </main>

    <footer>footer</footer>
  </div>
</template>

// 1sem/trvp/lab1/react/src/ui/Layout.tsx
import { Link, Outlet } from "react-router-dom";
import { Button } from "./Button";

export const Layout = () => {
  return (
    <>
      <header>
        <Link to={"/"}>СЕВЕРЯНОЧКА</Link>

        <Link to={"/cart"}>
          <Button isOrange>Корзина</Button>
        </Link>
      </header>
      <main>
        <Outlet />
      </main>
      <footer>footer</footer>
    </>
  );
};
