// 1sem/trvp/lab1/react/src/ui/Input.tsx
import { FC } from "react";

type InputProps = {
  label?: string;
  value?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  isDisabled?: boolean;
};

export const Input: FC<InputProps> = ({
  label,
  value,
  onChange,
  isDisabled,
}) => {
  return (
    <label className="ui_input-label">
      <span>{label}</span>
      <input
        className="ui_input-field"
        type="text"
        value={value}
        onChange={onChange}
        disabled={isDisabled}
      />
    </label>
  );
};

// 1sem/trvp/lab1/vue/src/ui/Input.vue
<script>
export default {
  name: "Input",
  props: {
    label: {
      type: String,
      default: "",
    },
    value: {
      type: String,
      default: "",
    },
    onChange: {
      type: Function,
      default: null,
    },
    isDisabled: {
      type: Boolean,
      default: false,
    },
  },
  methods: {
    handleInput(event) {
      if (this.onChange) {
        this.onChange(event);
      }
    },
  },
};
</script>

<template>
  <label class="ui_input-label">
    <span>{{ label }}</span>
    <input
      class="ui_input-field"
      type="text"
      :value="value"
      @input="handleInput"
      :disabled="isDisabled"
    />
  </label>
</template>
