// 1sem/trvp/lab1/svelte/src/ui/Raiting.svelte
<script>
  import Star from "./Star.svelte";

  export let starsSelected = 0;
  export let totalStars = 5;
  export let onRate = () => {};

  let stars = starsSelected;

  const clickStar = (i) => {
    onRate(i + 1);
    stars = i + 1;
  };
</script>

<div class="star-rating">
  {#each Array(totalStars) as _, i}
    <Star selected={i < stars} onClick={() => clickStar(i)} />
  {/each}
</div>

// 1sem/trvp/lab1/vue/src/ui/Raiting.vue
<script>
import { ref } from "vue";
import Star from "./Star.vue";

export default {
  name: "Rating",
  components: {
    Star,
  },
  props: {
    starsSelected: {
      type: Number,
      required: true,
    },
    totalStars: {
      type: Number,
      default: 5,
    },
    onRate: {
      type: Function,
      default: () => {},
    },
  },
  setup(props) {
    const stars = ref(props.starsSelected);

    const clickStar = (i) => {
      props.onRate(i + 1);
      stars.value = i + 1;
    };

    return {
      stars,
      clickStar,
    };
  },
};
</script>

<template>
  <div class="star-rating">
    <Star
      v-for="(n, i) in totalStars"
      :key="i"
      :selected="i < stars"
      @click="clickStar(i)"
    />
  </div>
</template>
