// 1sem/trvp/lab1/react/src/App.tsx
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { Layout } from "./ui";
import { Cart, Main } from "./pages";
import { useEffect } from "react";

function App() {
  useEffect(() => {
    const cart = localStorage.getItem("cart");
    if (!cart) localStorage.setItem("cart", JSON.stringify([]));
  }, []);

  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Layout />}>
          <Route index element={<Main />} />
          <Route path="cart" element={<Cart />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

export default App;

// 1sem/trvp/lab1/svelte/src/App.svelte
<script>
  import { Router, Route, Link } from "svelte-routing";
  import Layout from "./ui/Layout.svelte";
  import Main from "./pages/Main.svelte";
  import Cart from "./pages/Cart.svelte";

  const initializeCart = () => {
    const cart = localStorage.getItem("cart");
    if (!cart) localStorage.setItem("cart", JSON.stringify([]));
  };

  initializeCart();
</script>

<Router>
  <Layout>
    <Route path="/" component={Main} />
    <Route path="cart" component={Cart} />
  </Layout>
</Router>
