// 1sem/trvp/lab1/react/src/components/Card.tsx
import { FC, useEffect, useState } from "react";
import { Product } from "../types";
import { Button, Raiting } from "../ui";

type CardProps = {
  product: Product;
};

export const Card: FC<CardProps> = ({
  product: { cost, image, inCart, name, raiting, id },
}) => {
  const [isInCart, setIsInCart] = useState(inCart);

  const addToCart = () => {
    const cart: number[] = JSON.parse(localStorage.getItem("cart") as string);
    if (isInCart) {
      setIsInCart(false);
      localStorage.setItem(
        "cart",
        JSON.stringify(cart.filter((item) => item !== id))
      );
    } else {
      setIsInCart(true);

      cart.push(id);
      localStorage.setItem("cart", JSON.stringify(cart));
    }
  };

  useEffect(() => {
    const cart: number[] = JSON.parse(localStorage.getItem("cart") as string);
    if (cart.includes(id)) setIsInCart(true);
  }, []);

  return (
    <div className="product-card">
      <div className="product-card_image">
        <img src={image} alt={name} />
      </div>
      <div className="product-card_footer">
        <div className="product-card_cost">{cost} ₽</div>
        <div>{name}</div>
        <Raiting starsSelected={raiting} totalStars={5} />
        <Button isOrange={isInCart} onClick={addToCart}>
          В корзину
        </Button>
      </div>
    </div>
  );
};

// 1sem/trvp/lab1/svelte/src/components/Card.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Button from "../ui/Button.svelte";
  import Raiting from "../ui/Raiting.svelte";
  import type { Product } from "../types";
  export let product = {} as Product;

  let isInCart = product.inCart;

  const addToCart = () => {
    const cart: number[] =
      JSON.parse(localStorage.getItem("cart") as string) || [];
    if (isInCart) {
      isInCart = false;
      localStorage.setItem(
        "cart",
        JSON.stringify(cart.filter((item) => item !== product.id))
      );
    } else {
      isInCart = true;
      cart.push(product.id);
      localStorage.setItem("cart", JSON.stringify(cart));
    }
  };

  onMount(() => {
    const cart = JSON.parse(localStorage.getItem("cart") as string) || [];
    if (cart.includes(product.id)) {
      isInCart = true;
    }
  });
</script>

<div class="product-card">
  <div class="product-card_image">
    <img src={product.image} alt={product.name} />
  </div>
  <div class="product-card_footer">
    <div class="product-card_cost">{product.cost} ₽</div>
    <div>{product.name}</div>
    <Raiting starsSelected={product.raiting} totalStars={5} />
    <Button isOrange={isInCart} onClick={addToCart}>В корзину</Button>
  </div>
</div>
