// 1sem/trvp/lab1/react/src/pages/Cart.tsx
import { Card, Form } from "../components";
import { PRODUCTS_LIST } from "../data";
import { Product } from "../types";

export const Cart = () => {
  const cart: number[] = JSON.parse(localStorage.getItem("cart") as string);
  let cartItems: Product[] = [];
  PRODUCTS_LIST.forEach(({ products }) => cartItems.push(...products));

  cartItems = cartItems.filter(({ id }) => cart.includes(id));

  return (
    <div className="cart">
      <div className="cart_products">
        {cartItems.map((product) => (
          <Card product={product} key={product.id} />
        ))}
      </div>
      <div className="cart_delivery">
        <Form />
      </div>
    </div>
  );
};

// 1sem/trvp/lab1/svelte/src/pages/Cart.svelte
<script lang="ts">
  import Card from "../components/Card.svelte";
  import Form from "../components/Form.svelte";
  import { PRODUCTS_LIST } from "../data";
  import type { Product } from "../types";

  let cart = JSON.parse(localStorage.getItem("cart") as string) || [];
  let cartItems: Product[] = [];

  PRODUCTS_LIST.forEach(({ products }) => {
    cartItems.push(...products);
  });

  cartItems = cartItems.filter(({ id }) => cart.includes(id));
</script>

<div class="cart">
  <div class="cart_products">
    {#each cartItems as product (product.id)}
      <Card {product} />
    {/each}
  </div>
  <div class="cart_delivery">
    <Form />
  </div>
</div>
