// 1sem/trvp/lab1/svelte/src/components/Goods.svelte
<script>
  import Card from "./Card.svelte";
  export let productLists = [];
</script>

{#each productLists as { title, products }}
  <div class="goods" key={title}>
    <h3 class="goods_title">{title}</h3>
    <div class="goods_products">
      {#each products as product}
        <Card {product} key={product.name + product.cost} />
      {/each}
    </div>
  </div>
{/each}

// 1sem/trvp/lab1/vue/src/components/Goods.vue
<script>
import Card from "./Card.vue";

export default {
  name: "Goods",
  components: {
    Card,
  },
  props: {
    productLists: {
      type: Array,
      required: true,
    },
  },
};
</script>

<template>
  <div v-for="list in productLists" :key="list.title" class="goods">
    <h3 class="goods_title">{{ list.title }}</h3>
    <div class="goods_products">
      <Card
        v-for="product in list.products"
        :key="product.name + product.cost"
        :product="product"
      />
    </div>
  </div>
</template>
