// 1sem/trvp/lab1/svelte/src/components/Goods.svelte
<script>
  import Card from "./Card.svelte";
  export let productLists = [];
</script>

{#each productLists as { title, products }}
  <div class="goods" key={title}>
    <h3 class="goods_title">{title}</h3>
    <div class="goods_products">
      {#each products as product}
        <Card {product} key={product.name + product.cost} />
      {/each}
    </div>
  </div>
{/each}

// 1sem/trvp/lab1/react/src/components/Goods.tsx
import { FC } from "react";
import { ProductsList } from "../types";
import { Card } from "./Card";

type GoodsProps = {
  productLists: ProductsList[];
};

export const Goods: FC<GoodsProps> = ({ productLists }) => {
  return (
    <>
      {productLists.map(({ title, products }) => (
        <div key={title} className="goods">
          <h3 className="goods_title">{title}</h3>
          <div className="goods_products">
            {products.map((product) => (
              <Card product={product} key={product.name + product.cost} />
            ))}
          </div>
        </div>
      ))}
    </>
  );
};
