// 1sem/trvp/lab1/react/src/ui/Input.tsx
import { FC } from "react";

type InputProps = {
  label?: string;
  value?: string;
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  isDisabled?: boolean;
};

export const Input: FC<InputProps> = ({
  label,
  value,
  onChange,
  isDisabled,
}) => {
  return (
    <label className="ui_input-label">
      <span>{label}</span>
      <input
        className="ui_input-field"
        type="text"
        value={value}
        onChange={onChange}
        disabled={isDisabled}
      />
    </label>
  );
};

// 1sem/trvp/lab1/svelte/src/ui/Input.svelte
<script lang="ts">
  export let label = "";
  export let value = "";
  export let isDisabled = false;

  const handleChange = (event: any) => {
    value = event.target!.value;
  };
</script>

<label class="ui_input-label">
  <span>{label}</span>
  <input
    class="ui_input-field"
    type="text"
    bind:value
    on:input={handleChange}
    disabled={isDisabled}
  />
</label>
