// 1sem/trvp/lab1/react/src/ui/Raiting.tsx
import React, { FC, useState } from "react";

type StarProps = {
  selected?: boolean;
  onClick?: (a: any) => any;
};

const Star: FC<StarProps> = ({ selected = false, onClick = (f) => f }) => (
  <div className={selected ? "star selected" : "star"} onClick={onClick}></div>
);

type RaitingProps = {
  starsSelected: number;
  totalStars?: number;
  onRate?: (a: any) => any;
};

export const Raiting: FC<RaitingProps> = ({
  starsSelected,
  totalStars = 5,
  onRate = (f) => f,
}) => {
  const [stars, setStars] = useState(starsSelected);

  const clickStar = (i: number) => {
    onRate(i + 1);
    setStars(i + 1);
  };

  return (
    <div className="star-rating">
      {[...Array(totalStars)].map((n, i) => (
        <Star key={i} selected={i < stars} onClick={() => clickStar(i)} />
      ))}
    </div>
  );
};

// 1sem/trvp/lab1/svelte/src/ui/Raiting.svelte
<script>
  import Star from "./Star.svelte";

  export let starsSelected = 0;
  export let totalStars = 5;
  export let onRate = () => {};

  let stars = starsSelected;

  const clickStar = (i) => {
    onRate(i + 1);
    stars = i + 1;
  };
</script>

<div class="star-rating">
  {#each Array(totalStars) as _, i}
    <Star selected={i < stars} onClick={() => clickStar(i)} />
  {/each}
</div>
